<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#데이터-입/출력" data-toc-modified-id="데이터-입/출력-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>데이터 입/출력</a></span><ul class="toc-item"><li><span><a href="#File/path/directory-check" data-toc-modified-id="File/path/directory-check-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>File/path/directory check</a></span></li><li><span><a href="#read-and-write-with-pickle" data-toc-modified-id="read-and-write-with-pickle-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>read and write with pickle</a></span></li><li><span><a href="#pickle-with-dict" data-toc-modified-id="pickle-with-dict-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>pickle with dict</a></span></li><li><span><a href="#Pandas-library" data-toc-modified-id="Pandas-library-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Pandas library</a></span></li></ul></li><li><span><a href="#read-and-write-with-Pandas" data-toc-modified-id="read-and-write-with-Pandas-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>read and write with Pandas</a></span><ul class="toc-item"><li><span><a href="#Constructing-DataFrame" data-toc-modified-id="Constructing-DataFrame-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Constructing DataFrame</a></span></li><li><span><a href="#Changing-index" data-toc-modified-id="Changing-index-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Changing index</a></span></li><li><span><a href="#indexing-and-selecting-data" data-toc-modified-id="indexing-and-selecting-data-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>indexing and selecting data</a></span><ul class="toc-item"><li><span><a href="#loc과-iloc" data-toc-modified-id="loc과-iloc-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>loc과 iloc</a></span></li><li><span><a href="#Manipulating-components" data-toc-modified-id="Manipulating-components-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Manipulating components</a></span></li><li><span><a href="#datetime" data-toc-modified-id="datetime-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>datetime</a></span></li></ul></li></ul></li></ul></div>

# 데이터 입/출력
- 데이터 분석을 위해서는 데이터를 python으로 불러들여야 함
- 분석결과를 저장하기 위해서는 pickle (or joblib) module이 사용됨 (pkl 확장자)


- Reading
    - fin = open('file.txt', 'r') (open()은 built-in function)
    - 'r': read
    - binary 파일을 읽으려면 'rb' 사용
<br><br>
- Writing
    - fout = open('file.txt', 'w')
    - 'w': write. 파일이 존재할 시에 덮어씀. 존재하지 않는 경우에는 파일을 생성
    - binary 파일에 쓰려면 'wb' 사용
<br><br>
- default location
    - import os
    - print(os.getcwd())
    

- 파일 위치를 absolute path로 지정하지 않을 시 (e.g. "C:/myFolder/file.txt"), relative path로 인식하여 cwd에 파일을 생성함

## File/path/directory check

In [19]:
import os

fout = open('output.txt', 'w') # open(): built-in function
line1 = "A line to write.\n"
fout.write(line1)
fout.close()

filePath1 = 'C:/local/'
filePath2 = 'C:/local/myCode.py'
for filePath in [filePath1, filePath2]:
    print('varname: %s' % filePath)
    print(os.path.exists(filePath)) # checks whether a file or directory exists
    print(os.path.isdir(filePath)) # checks whether "filePath" is a directory
    print(os.path.isfile(filePath)) # checks whether "filePath" is a file
    print('')

varname: C:/local/
True
True
False

varname: C:/local/myCode.py
True
False
True



## read and write with pickle
- pickle에서는 binary file로 작업을 해야 함

In [2]:
# ex 1) 배열 크기가 10000인 난수를 생성해서 result.pkl 파일로 저장

import os
path = 'C:/test/' 
import numpy as np
_rnd = np.random.rand(10000) # uniform dist [0, 1]

import pickle
if not os.path.exists(path): # C:/test/ 폴더가 존재하지 않으면
    os.mkdir(path) # 해당 위치에 해당 폴더를 생성

    
# 파일 저장
pkl_file = open(path + 'data.pkl', 'wb') # open file for writing
pickle.dump(_rnd, pkl_file) # write _rnd to pkl_file
pkl_file.close() # close file after use


In [3]:
# 파일 불러오기
pkl_file = open(path + 'data.pkl', 'rb') # open file for reading
_rnd_load = pickle.load(pkl_file) # PKL 파일에 저장한 후 불러들인 변수
pkl_file.close()
print(_rnd[:5]) # 기존에 저장되어 있던 변수
print(_rnd_load[:5]) # PKL 파일에 저장한 후 불러들인 변수


# 두 변수가 같은지를 확인
print(_rnd[2] == _rnd_load[2])
print(np.equal(_rnd, _rnd_load)) # element-wise equality check
print(np.array_equal(_rnd, _rnd_load)) # 모든 element에 대해 element-wise equality가 성립하면 True

[0.1536688  0.91436494 0.99773698 0.646381   0.71887732]
[0.1536688  0.91436494 0.99773698 0.646381   0.71887732]
True
[ True  True  True ...  True  True  True]
True


In [28]:
# ex 1) 배열 크기가 10000인 난수를 생성해서 result.pkl 파일로 저장

path = 'C:/test/' 
import numpy as np
_rnd = np.random.rand(10000) # uniform dist [0, 1]

import pickle
if not os.path.exists(path): # C:/test/ 폴더가 존재하지 않으면
    os.mkdir(path) # 해당 위치에 해당 폴더를 생성

    
# 파일 저장
pkl_file = open(path + 'data.pkl', 'wb') # open file for writing
pickle.dump(_rnd, pkl_file) # write _rnd to pkl_file
pkl_file.close() # close file after use

# 파일 불러오기
pkl_file = open(path + 'data.pkl', 'rb') # open file for reading
_rnd_load = pickle.load(pkl_file) # PKL 파일에 저장한 후 불러들인 변수
pkl_file.close()
print(_rnd[:5]) # 기존에 저장되어 있던 변수
print(_rnd_load[:5]) # PKL 파일에 저장한 후 불러들인 변수


# 두 변수가 같은지를 확인
print(_rnd[2] == _rnd_load[2])
print(np.equal(_rnd, _rnd_load)) # element-wise equality check
print(np.array_equal(_rnd, _rnd_load)) # 모든 element에 대해 element-wise equality가 성립하면 True

[0.05981184 0.52618407 0.56861823 0.00996738 0.03830634]
[0.05981184 0.52618407 0.56861823 0.00996738 0.03830634]
True
[ True  True  True ...  True  True  True]
True


In [4]:
# ex 2)
pkl_file = open(path + 'data.pkl', 'wb')
pickle.dump(_rnd, pkl_file)
pickle.dump(_rnd * 100, pkl_file) # 같은 pkl_file에 이어서 저장됨
pkl_file.close()

pkl_file = open(path + 'data.pkl', 'rb')
x = pickle.load(pkl_file) # x == _rnd
y = pickle.load(pkl_file) # y == _rnd * 100
pkl_file.close()

## pickle with dict
- pickle은 FIFO (First In, First Out) 형태로 저장됨.
    - ex 2)에서는 _rnd가 먼저 저장되고, _rnd*100의 값이 그 뒤에 저장됨
    

- pkl file을 직접 불러들여 확인하기 전까지는 파일 내부에 어떤 정보가 저장되어 있는지 알 수 없음. 
- 이를 피하기 위해서 위의 ex 2)에서처럼 같은 pkl 파일에 나눠서 저장하는 대신에, dict를 사용해서 한 번에 저장이 가능

In [29]:
# ex 3)
pkl_file = open(path + 'data.pkl', 'wb')
pickle.dump({'x' : x, 'y' : y}, pkl_file)
pkl_file.close()

pkl_file = open(path + 'data.pkl', 'rb')
data = pickle.load(pkl_file)
pkl_file.close()

for key in data.keys():
    print (key, data[key][:5]) # key 이름과 각 key에 해당하는 변수의 처음 5번째 component를 확인

x [0.36619901 0.53335147 0.76495175 0.39376967 0.17425838]
y [36.61990106 53.3351469  76.49517504 39.37696739 17.42583808]


## Pandas library
- 금융에서 일반적으로 사용하는 파일 형식으로는 txt, csv, xls/xlsx, sql 등이 있으며, 대부분 column (identifier)과 row (observation)으로 이루어져 있음. 
    - row: 관측 시점
    - column: 주가, 수익률, 기업 티커, ...
    - index: row에 대한 label을 제공. 일반적으로 관측시점 혹은 기업명을 사용 (혹은 이들을 포함한 변수들; MultiIndex)


- 이를 다루기 위해 일반적으로 pandas library를 사용
    - 행과 열로 구분된 데이터베이스 (tabular database)를 다룰 수 있는 DataFrame이라는 틀을 제공
    

- Pandas library를 통해 csv, xlsx 형식의 파일을 저장 가능

# read and write with Pandas

In [ ]:
import pandas as pd
path = 'C:/test/'
pd.read_csv(path + 'data.txt') # read txt
pd.read_csv(path + 'data.csv') # read csv
pd.read_excel(path + 'data.xlsx') # read xlsx
pd.read_sas(path + 'data.sas7bdat') # read SAS data
pd.read_stata(path + 'data.dta') # read STATA data

pd.to_csv(path + 'data.csv') # write csv
pd.to_excel(path + 'data.xlsx') # write xlsx

## Constructing DataFrame

In [9]:
# dataframe 생성
import pandas as pd
df = pd.DataFrame([10, 20, 30, 40], columns=['numbers'], index=['a', 'b', 'c', 'd'])
# df = pd.DataFrame([10, 20, 30, 40], columns=['numbers']) # index를 따로 입력하지 않으면 자동으로 0, 1, 2,... 를 생성
display(df)

numbers
a       10
b       20
c       30
d       40

In [10]:
# column / 변수 추가
df['alphabet'] = ['a', 'b', 'c', 'd']
display(df)

numbers alphabet
a       10        a
b       20        b
c       30        c
d       40        d

In [11]:
index = df.index
val = df.values

print(f'index: {index}\n') # returns index object
print(f'index.values: {list(index.values)}\n') # value of index as a list

print(f'val: {val}\n') # whole values of columns
print(f'val.shape: {val.shape}')

index: Index(['a', 'b', 'c', 'd'], dtype='object')

index.values: ['a', 'b', 'c', 'd']

val: [[10 'a']
 [20 'b']
 [30 'c']
 [40 'd']]

val.shape: (4, 2)


## Changing index

In [12]:
# index 값 변경
df.index = ['1996-01-01', '2000-01-01', '2010-01-01','2020-01-01']
display(df)

numbers alphabet
1996-01-01       10        a
2000-01-01       20        b
2010-01-01       30        c
2020-01-01       40        d

## indexing and selecting data
### loc과 iloc
- .loc을 통해 label based로 DataFrame의 값에 접근 가능
- .iloc을 통해 integer position based로 DataFrame 값에 접근 가능
    - 가능한 한 iloc을 쓰지 않는 것을 권장. iloc으로 접근 시, 해당 변수가 몇 번째 변수인가를 확인해야 하는 번거로움이 있음

In [14]:
numbers1 = df['numbers'] # 'numbers' 변수의 값을 numbers1 변수에 할당
numbers2 = df.loc[:, 'numbers'] # 다른 문법, 같은 결과

numbers3 = df.iloc[:, 0] # 0: 0번째 column

print(numbers1, numbers2, numbers3, sep='\n\n')

1996-01-01    10
2000-01-01    20
2010-01-01    30
2020-01-01    40
Name: numbers, dtype: int64

1996-01-01    10
2000-01-01    20
2010-01-01    30
2020-01-01    40
Name: numbers, dtype: int64

1996-01-01    a
2000-01-01    b
2010-01-01    c
2020-01-01    d
Name: alphabet, dtype: object


- df.loc[:, 'colname']으로 colname에 해당하는 column 전체를 select 가능
    - df['colname']도 가능


- df.loc['index', :] 으로 index에 해당하는 row 전체를 select 가능


- df.loc['rowname', 'colname']으로 component 하나를 select 가능


- 여러 개의 row와 column을 선택하고 싶을 시 ['rowname1', 'rowname2'] 형태의 list를 이용

In [15]:
print(df[['numbers', 'alphabet']])
print('\n')

# selecting or slicing
print(df['numbers'][:2])
print('-'*80)

print('\n')
print(df['numbers'][3])
print('-'*80)

print('\n')
print(df.loc[:, 'numbers'][:2])

            numbers alphabet
1996-01-01       10        a
2000-01-01       20        b
2010-01-01       30        c
2020-01-01       40        d


1996-01-01    10
2000-01-01    20
Name: numbers, dtype: int64
--------------------------------------------------------------------------------


40
--------------------------------------------------------------------------------


1996-01-01    10
2000-01-01    20
Name: numbers, dtype: int64


### Manipulating components

In [16]:
# ex) loc
display(df)

df.loc['1996-01-01', 'numbers'] = 70 #  'numbers' column의 '1996-01-01' row의 값을 30으로 바꿈
display(df)

df.loc['2010-01-01', 'alphabet'] *= 2 # 'alphabet' column의 '2010-01-01' row의 값에 *2 연산을 함
display(df)

import copy
df_ = copy.deepcopy(df)
df_.loc[0, 'numbers'] = 130 # index가 0인 row, 'numbers' column에 대해 새로운 entry가 생성됨 (주의: 0번째 row를 바꾸는 것이 아님)
display('df_:', df_)

numbers alphabet
1996-01-01       10        a
2000-01-01       20        b
2010-01-01       30        c
2020-01-01       40        d

numbers alphabet
1996-01-01       70        a
2000-01-01       20        b
2010-01-01       30        c
2020-01-01       40        d

numbers alphabet
1996-01-01       70        a
2000-01-01       20        b
2010-01-01       30       cc
2020-01-01       40        d

'df_:'

numbers alphabet
1996-01-01     70.0        a
2000-01-01     20.0        b
2010-01-01     30.0       cc
2020-01-01     40.0        d
0             130.0      NaN

In [129]:
# ex) iloc
df.iloc[3, 1] = 100 # 3번째 row, 1번째 column의 값을 100으로 바꿈
display(df)

# 3번째 row는 '2020-01-01', 1번째 column은 'alphabet' column에 해당

numbers alphabet
1996-01-01       70        a
2000-01-01       20        b
2010-01-01       30       cc
2020-01-01       40      100

### datetime
- Pandas library를 통해 string을 datetime으로 변환 가능
- str일 때에는 pandas에서 제공하는 date에 대한 여러 함수들을 사용할 수 없음

In [17]:
type('1996-01-01')

str

In [119]:
# pd.to_datetime()을 통해 date format의 string object를 DateTimeIndex object로 변환 가능
str2datetime = pd.to_datetime(df.index)
print(str2datetime)
print(type(str2datetime))

DatetimeIndex(['1996-01-01', '2000-01-01', '2010-01-01', '2020-01-01',
               '1970-01-01'],
              dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
